site_name: Project Z
site_url: https://fidyback.github.io/Projeto_Z_de_Jogo
repo_url: https://github.com/FidyBack/Projeto_Z_de_Jogo
site_author: Abel Cavalcante
nav:
  - Home: index.md
  - Installation: installation.md
theme:
    name: dracula
markdown_extensions:
  - attr_list
  - md_in_html
